/* ===================================================================
   SNEHAKOOTA ACCOUNT WIDGET — logic
   Version: 10.1
   =================================================================== */
(function(){
  "use strict";
  var mount=document.getElementById('sk-account-root');
  if(!mount)return;
  var SUPABASE_URL='https://hukfpoxvtutvhjfdzcuh.supabase.co';
  var SUPABASE_PUBLISHABLE_KEY='sb_publishable_6_9Fc319vRsSZSksFlhzSw_28-glehH';
  var INVITATION_MEMBERSHIP_MODE='optional';
  var INVITATION_SHOW_GENERAL_OPTION=true;
  var INVITATION_SUCCESS_MESSAGE_MS=2500;
  var INVITATION_CONTEXT_STORAGE_KEY='snehakoota.invitation.context.v1';
  var INVITATION_AUTH_PENDING_STORAGE_KEY='snehakoota.invitation.auth-pending.v1';
  if(!window.supabase){console.error('account.js: supabase-js must be loaded before this script.');return;}
  var supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',experimental:{passkey:true}}});
  var receiverInvitationContext={code:null,valid:false,data:null,source:'none',selectedMembershipIds:[]};
  var receiverExistingMemberships=[];
  var receiverExistingMembershipsLoaded=false;
  var receiverInvitationAutoOpened=false;
  var receiverInvitationProcessing=false;
  var receiverInvitationAuthProcessing=false;

  function normalizeInvitationCode(value){var code=String(value||'').trim().toUpperCase();return /^[A-Z0-9]{8}$/.test(code)?code:null;}
  function readInvitationCodeFromUrl(){try{return normalizeInvitationCode(new URLSearchParams(window.location.search).get('invite'));}catch(e){return null;}}
  function loadStoredInvitationContext(){try{var raw=sessionStorage.getItem(INVITATION_CONTEXT_STORAGE_KEY);if(!raw)return null;var parsed=JSON.parse(raw);var code=normalizeInvitationCode(parsed&&parsed.code);if(!code)return null;return{code:code,valid:parsed.valid===true,data:parsed.data||null,selectedMembershipIds:Array.isArray(parsed.selectedMembershipIds)?parsed.selectedMembershipIds.map(Number).filter(Number.isFinite):[],source:'session'};}catch(e){return null;}}
  function saveInvitationContext(context){try{sessionStorage.setItem(INVITATION_CONTEXT_STORAGE_KEY,JSON.stringify(context));}catch(e){}}
  function markInvitationAuthPending(){try{if(receiverInvitationContext.valid)sessionStorage.setItem(INVITATION_AUTH_PENDING_STORAGE_KEY,'1');}catch(e){}}
  function clearInvitationAuthPending(){try{sessionStorage.removeItem(INVITATION_AUTH_PENDING_STORAGE_KEY);}catch(e){}}
  function hasInvitationAuthPending(){try{return sessionStorage.getItem(INVITATION_AUTH_PENDING_STORAGE_KEY)==='1';}catch(e){return false;}}
  function clearInvitationContext(){try{sessionStorage.removeItem(INVITATION_CONTEXT_STORAGE_KEY);}catch(e){}clearInvitationAuthPending();receiverInvitationContext={code:null,valid:false,data:null,source:'none',selectedMembershipIds:[]};receiverExistingMemberships=[];receiverExistingMembershipsLoaded=false;receiverInvitationAutoOpened=false;receiverInvitationAuthProcessing=false;}
  function receiverInvitationProposals(){var proposals=receiverInvitationContext&&receiverInvitationContext.data&&Array.isArray(receiverInvitationContext.data.proposals)?receiverInvitationContext.data.proposals:[];return proposals;}
  function receiverInvitationExistingKey(row){return String(Number(row.school_id))+'|'+String(Number(row.batch_id));}
  function receiverInvitationProposalIsAlreadyActive(row){var key=receiverInvitationExistingKey(row);return receiverExistingMemberships.some(function(existing){return receiverInvitationExistingKey(existing)===key&&String(existing.status).toLowerCase()==='active';});}
  function receiverInvitationVisibleProposals(){return receiverInvitationProposals().filter(function(row){return !receiverInvitationProposalIsAlreadyActive(row);});}
  function receiverInvitationSelectedMembershipIds(){var stored=loadStoredInvitationContext();var visibleIds=receiverInvitationVisibleProposals().map(function(row){return Number(row.membership_id);}).filter(Number.isFinite);if(stored&&Array.isArray(stored.selectedMembershipIds))return stored.selectedMembershipIds.filter(function(id){return visibleIds.indexOf(Number(id))!==-1;});return visibleIds.slice();}
  function receiverInvitationIsGeneral(){return !!(receiverInvitationContext.valid&&receiverInvitationContext.data&&receiverInvitationContext.data.invitation_kind==='general');}
  function receiverInvitationHasProcessableSelection(){return receiverInvitationIsGeneral()||receiverInvitationSelectedMembershipIds().length>0;}
  function persistReceiverMembershipSelection(){var ids=[];document.querySelectorAll('#skaReceiverInvitationOptions input[data-membership-id]:checked').forEach(function(input){ids.push(Number(input.getAttribute('data-membership-id')));});receiverInvitationContext.selectedMembershipIds=ids;saveInvitationContext(receiverInvitationContext);}
  function receiverInvitationOptionChange(){persistReceiverMembershipSelection();}
  function renderReceiverInvitationContext(){if(!receiverInvitationContext.valid||!receiverInvitationContext.data)return '';var proposals=receiverInvitationVisibleProposals();if(!proposals.length){return '<div class="ska-receiver-invite-context"><div class="ska-receiver-invite-label">Invitation</div><div class="ska-receiver-invite-note">You already have the membership included in this invitation.</div></div>';}var selected=receiverInvitationSelectedMembershipIds();var options=proposals.map(function(row){var id=Number(row.membership_id);var checked=selected.indexOf(id)!==-1?' checked':'';var school=row.school_name||'Snehakoota';var batch=row.batch_year?String(row.batch_year):'';return '<label class="ska-receiver-invite-option"><input type="checkbox" data-membership-id="'+id+'"'+checked+'><span><strong>'+school+'</strong><small>'+batch+'</small></span></label>';}).join('');var note=receiverInvitationProposals().length===proposals.length?'You arrived through a Snehakoota invitation.':'Choose the membership(s) you want to join.';return '<div class="ska-receiver-invite-context"><div class="ska-receiver-invite-label">Invitation</div><div class="ska-receiver-invite-note">'+note+'</div><div class="ska-receiver-invite-memberships" id="skaReceiverInvitationOptions">'+options+'</div></div>';}
  function bindReceiverInvitationContext(){document.querySelectorAll('#skaReceiverInvitationOptions input[data-membership-id]').forEach(function(input){input.addEventListener('change',receiverInvitationOptionChange);});}
  function renderReceiverProcessingAction(){if(!receiverInvitationContext.valid||!receiverInvitationContext.data)return '';var visible=receiverInvitationVisibleProposals();if(receiverInvitationIsGeneral())return '<div class="ska-receiver-invite-actions"><button type="button" class="ska-provider-btn ska-secondary" id="skaConfirmInvitation">Confirm</button><button type="button" class="ska-signout-btn" id="skaIgnoreInvitation">Ignore</button></div><div class="ska-message" id="skaInvitationProcessMessage"></div>';if(!visible.length)return '';return '<div class="ska-receiver-invite-actions"><button type="button" class="ska-provider-btn ska-secondary" id="skaConfirmInvitation">Confirm</button><button type="button" class="ska-signout-btn" id="skaIgnoreInvitation">Ignore</button></div><div class="ska-message" id="skaInvitationProcessMessage"></div>';}
  function invitationProposalForMembership(membershipId,proposalSnapshot){var id=Number(membershipId);var proposals=Array.isArray(proposalSnapshot)?proposalSnapshot:receiverInvitationProposals();return proposals.filter(function(row){return Number(row.membership_id)===id;})[0]||null;}
  function formatReceiverStatus(status){var value=String(status||'').toLowerCase();return value?value.charAt(0).toUpperCase()+value.slice(1):'Pending';}
  function renderReceiverOutcome(result,proposalSnapshot){var memberships=Array.isArray(result&&result.memberships)?result.memberships:[];if(!memberships.length)return '<div class="ska-message ska-receiver-outcome"><strong>Your Snehakoota invitation is complete.</strong></div>';var rows=memberships.map(function(item){var proposal=invitationProposalForMembership(item.membership_id,proposalSnapshot);var school=proposal&&proposal.school_name?proposal.school_name:'Snehakoota';var batch=proposal&&proposal.batch_year?String(proposal.batch_year):'';return '<div><strong>'+school+(batch?' • '+batch:'')+'</strong> &nbsp; ✓ '+formatReceiverStatus(item.status)+'</div>';}).join('');return '<div class="ska-receiver-outcome">'+rows+'</div>';}
  function renderSignedInOutcome(session,result,proposalSnapshot){currentSession=session;var user=session.user;body.innerHTML='<h3 class="ska-auth-title">Signed in</h3><div class="ska-identity"><strong>'+displayName(user)+'</strong><span>'+ (user.email||'Google account')+'</span></div>'+renderReceiverOutcome(result,proposalSnapshot)+inviteEntry()+'<button type="button" class="ska-provider-btn ska-secondary" id="skaRegisterPasskey">'+PASSKEY_ICON+'<span>Add a passkey to this device</span></button><button type="button" class="ska-signout-btn" id="skaSignOut">Sign out</button><div class="ska-message" id="skaMessage"></div>';bindSignedInControls();}
  function loadReceiverMembershipsForInvitation(){if(!currentSession||!receiverInvitationContext.valid||receiverInvitationIsGeneral()){receiverExistingMembershipsLoaded=true;return Promise.resolve([]);}receiverExistingMembershipsLoaded=false;return supabaseClient.rpc('get_my_memberships').then(function(res){if(res.error){console.error('Receiver membership loading error:',res.error);receiverExistingMemberships=[];receiverExistingMembershipsLoaded=true;return[];}receiverExistingMemberships=res.data||[];receiverExistingMembershipsLoaded=true;return receiverExistingMemberships;}).catch(function(err){console.error('Receiver membership loading error:',err);receiverExistingMemberships=[];receiverExistingMembershipsLoaded=true;return[];});}
  function renderSignedInWithInvitation(){currentSession=currentSession;var user=currentSession.user;var waiting='<div class="ska-message">Checking your current memberships…</div>';body.innerHTML=waiting;loadReceiverMembershipsForInvitation().then(function(){if(!currentSession)return;body.innerHTML=renderReceiverInvitationContext()+renderReceiverProcessingAction()+'<h3 class="ska-auth-title">Signed in</h3><div class="ska-identity"><strong>'+displayName(user)+'</strong><span>'+ (user.email||'Google account')+'</span></div>'+inviteEntry()+'<button type="button" class="ska-provider-btn ska-secondary" id="skaRegisterPasskey">'+PASSKEY_ICON+'<span>Add a passkey to this device</span></button><button type="button" class="ska-signout-btn" id="skaSignOut">Sign out</button><div class="ska-message" id="skaMessage"></div>';bindSignedInControls();});}
  function renderInvitationProcessingScreen(){if(!currentSession)return;var user=currentSession.user;body.innerHTML='<h3 class="ska-auth-title">Completing your invitation…</h3><div class="ska-identity"><strong>'+displayName(user)+'</strong><span>'+ (user.email||'Google account')+'</span></div><div class="ska-message" id="skaInvitationProcessMessage">Saving your membership selection…</div>';openSheet();}
  function processReceiverInvitation(){if(receiverInvitationProcessing||!currentSession||!receiverInvitationContext.valid)return;var message=document.getElementById('skaInvitationProcessMessage'),button=document.getElementById('skaConfirmInvitation');var selected=receiverInvitationSelectedMembershipIds();if(!receiverInvitationIsGeneral()&&!selected.length){if(message)message.textContent='No membership selected. Choose at least one membership to continue.';return;}var proposalSnapshot=receiverInvitationProposals().map(function(row){return{membership_id:Number(row.membership_id),school_name:row.school_name||'',batch_year:row.batch_year||null};});var processingCode=receiverInvitationContext.code;var isGeneral=receiverInvitationIsGeneral();receiverInvitationProcessing=true;if(button){button.disabled=true;button.textContent='Processing…';}var ignore=document.getElementById('skaIgnoreInvitation');if(ignore)ignore.disabled=true;if(message)message.textContent='Completing your invitation…';supabaseClient.rpc('process_invitation_memberships',{p_invitation_code:processingCode,p_selected_membership_ids:isGeneral?[]:selected}).then(function(res){if(res.error){console.error('Invitation processing error:',res.error);receiverInvitationProcessing=false;if(message)message.textContent='We could not complete the invitation. Please try again.';if(button){button.textContent='Confirm';button.disabled=false;}if(ignore)ignore.disabled=false;return;}var data=res.data||{};if(data.success!==true){console.error('Invitation processing failed:',data);receiverInvitationProcessing=false;if(message)message.textContent=data.message||'We could not complete the invitation. Please try again.';if(button){button.textContent='Confirm';button.disabled=false;}if(ignore)ignore.disabled=false;return;}receiverInvitationProcessing=false;clearInvitationContext();renderSignedInOutcome(currentSession,data,proposalSnapshot);}).catch(function(err){console.error('Invitation processing error:',err);receiverInvitationProcessing=false;if(message)message.textContent='We could not complete the invitation. Please try again.';if(button){button.textContent='Confirm';button.disabled=false;}if(ignore)ignore.disabled=false;});}
  function ignoreReceiverInvitation(){if(receiverInvitationProcessing)return;clearInvitationContext();if(currentSession){renderSignedIn(currentSession);closeSheet();}}
  function beginAuthenticatedInvitationProcessing(){if(receiverInvitationAuthProcessing||!currentSession)return;receiverInvitationAuthProcessing=true;var run=function(ctx){if(!ctx||ctx.valid!==true){receiverInvitationAuthProcessing=false;closeSheet();return;}if(!receiverInvitationContext.valid){var stored=loadStoredInvitationContext();if(stored&&stored.valid===true){receiverInvitationContext=stored;}}if(!receiverInvitationHasProcessableSelection()){receiverInvitationAuthProcessing=false;renderSignedInWithInvitation();return;}clearInvitationAuthPending();renderInvitationProcessingScreen();processReceiverInvitation();};if(receiverInvitationContext.valid)run(receiverInvitationContext);else{var stored=loadStoredInvitationContext();if(stored&&stored.valid===true){receiverInvitationContext=stored;run(receiverInvitationContext);}else if(typeof invitationResolutionPromise!=='undefined')invitationResolutionPromise.then(run).catch(function(){receiverInvitationAuthProcessing=false;});else{receiverInvitationAuthProcessing=false;}}
  }
  function maybeAutoOpenInvitation(){if(receiverInvitationAutoOpened||!receiverInvitationContext.valid||typeof openSheet!=='function')return;receiverInvitationAutoOpened=true;if(currentSession){renderSignedInWithInvitation();}else{renderSignedOut();bindReceiverInvitationContext();}window.setTimeout(function(){if(!sheet.classList.contains('ska-show'))openSheet();},0);}
  function resolveReceiverInvitationContext(){var urlCode=readInvitationCodeFromUrl();var stored=loadStoredInvitationContext();var code=urlCode||(stored&&stored.code)||null;if(!code){receiverInvitationContext={code:null,valid:false,data:null,source:'none',selectedMembershipIds:[]};return Promise.resolve(receiverInvitationContext);}var initialSelected=stored&&Array.isArray(stored.selectedMembershipIds)?stored.selectedMembershipIds:[];receiverInvitationContext={code:code,valid:false,data:null,source:urlCode?'url':'session',selectedMembershipIds:initialSelected};return supabaseClient.rpc('resolve_invitation',{p_invitation_code:code}).then(function(res){if(res.error){console.error('Invitation resolution error:',res.error);receiverInvitationContext={code:code,valid:false,data:null,source:urlCode?'url':'session',selectedMembershipIds:[]};}else{var data=res.data||{};var valid=data.success===true&&data.invitation_valid===true;var proposals=valid&&Array.isArray(data.proposals)?data.proposals:[];var proposalIds=proposals.map(function(row){return Number(row.membership_id);}).filter(Number.isFinite);var selected=initialSelected.filter(function(id){return proposalIds.indexOf(Number(id))!==-1;});if(!selected.length&&proposalIds.length)selected=proposalIds.slice();receiverInvitationContext={code:code,valid:valid,data:valid?data:null,selectedMembershipIds:valid?selected:[],source:urlCode?'url':'session'};}if(receiverInvitationContext.valid){saveInvitationContext(receiverInvitationContext);maybeAutoOpenInvitation();}else{try{sessionStorage.removeItem(INVITATION_CONTEXT_STORAGE_KEY);}catch(e){}clearInvitationAuthPending();}if(typeof sheet!=='undefined'&&sheet.classList.contains('ska-show')){if(currentSession)renderSignedInWithInvitation();else renderSignedOut();if(!currentSession)bindReceiverInvitationContext();}return receiverInvitationContext;}).catch(function(err){console.error('Invitation resolution error:',err);receiverInvitationContext={code:code,valid:false,data:null,source:urlCode?'url':'session',selectedMembershipIds:[]};try{sessionStorage.removeItem(INVITATION_CONTEXT_STORAGE_KEY);}catch(e){}return receiverInvitationContext;});}
  var invitationResolutionPromise=resolveReceiverInvitationContext();

  var GOOGLE_ICON='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.23c0-.72-.06-1.42-.18-2.09H12v3.96h5.23a4.47 4.47 0 0 1-1.94 2.93v2.43h3.14c1.84-1.69 2.92-4.18 2.92-7.23z"/><path fill="#34A853" d="M12 21.5c2.63 0 4.84-.87 6.45-2.37l-3.14-2.43c-.87-.92-1.98-.92-3.31-.92-2.54 0-4.69-1.72-5.46-4.03l3.24-2.5z"/><path fill="#FBBC05" d="M6.54 13.59A5.86 5.86 0 0 1 6.23 12c0-.55.11-1.08.31-1.59v-2.5H3.3A9.75 9.75 0 0 0 2.25 12c0 1.57.38 3.05 1.05 4.09l3.24-2.5z"/><path fill="#EA4335" d="M12 6.38c1.43 0 2.71 0.49 3.72 1.46l2.79-2.79C16.84 3.5 14.63 3.5 12 2.5a9.74 9.74 0 0 0-8.7 5.41l3.24 2.5c0.87-0.92 1.98-0.92 3.31-0.92 2.54 0 4.69-1.72 5.46-4.03l3.24-2.5z"/></svg>';
  var PASSKEY_ICON='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="8.5" cy="8.5" r="3.5"></circle><path d="M11 11l8 8M15 15l2-2M17 17l2-2"></path></svg>';
  var INVITE_ICON='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"></path><circle cx="9.5" cy="7" r="4"></circle><path d="M19 8v6M22 11h-6"></path></svg>';
  var providers=[
    {id:'google',label:'Continue with Google',style:'ska-primary',icon:GOOGLE_ICON,action:function(btn){if(btn)btn.disabled=true;markInvitationAuthPending();var redirectTo=window.location.origin+window.location.pathname;var message=document.getElementById('skaMessage');if(message)message.textContent='Google ಮೂಲಕ ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲಾಗುತ್ತಿದೆ…';supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirectTo,queryParams:{prompt:'select_account'}}}).then(function(res){if(res.error){console.error('Google sign-in error:',res.error);clearInvitationAuthPending();if(message)message.textContent='ಸೈನ್ ಇನ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';if(btn)btn.disabled=false;}});}},
    {id:'passkey',label:'Sign in with passkey',style:'ska-secondary',icon:PASSKEY_ICON,action:function(btn){if(btn)btn.disabled=true;markInvitationAuthPending();var message=document.getElementById('skaMessage');if(message)message.textContent='Passkey ಮೂಲಕ ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲಾಗುತ್ತಿದೆ…';if(!window.PublicKeyCredential||!navigator.credentials){clearInvitationAuthPending();if(message)message.textContent='ಈ ಸಾಧನ ಅಥವಾ ಬ್ರೌಸರ್‌ನಲ್ಲಿ Passkey ಬೆಂಬಲವಿಲ್ಲ.';if(btn)btn.disabled=false;return;}supabaseClient.auth.signInWithPasskey().then(function(res){if(res.error){console.error('Passkey sign-in error:',res.error);clearInvitationAuthPending();if(message){if(res.error.code==='webauthn_credential_not_found')message.textContent='ಈ ಖಾತೆಗೆ ಇನ್ನೂ Passkey ಸೇರಿಸಿಲ್ಲ. ಮೊದಲು ಖಾತೆ ಒಳಗೆ Passkey ಸೇರಿಸಿ.';else message.textContent='Passkey ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';}if(btn)btn.disabled=false;}});}}
  ];
  mount.innerHTML='<div class="ska-backdrop" id="skaBackdrop"></div><div class="ska-tray" id="skaTray"><button class="ska-trigger" id="skaTrigger" type="button" aria-label="Account" aria-expanded="false" aria-controls="skaSheet"><span class="ska-icon" id="skaIcon"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.2"></circle><path d="M5.5 19c.7-3.1 3-4.8 6.5-4.8s5.8 1.7 6.5 4.8"></path></svg><span class="ska-status" id="skaStatus"></span></span></button></div><div class="ska-sheet" id="skaSheet" role="dialog" aria-modal="true" aria-hidden="true"><div class="ska-sheet-top"><span class="ska-sheet-title">SnehaKoota Account</span><button class="ska-close" id="skaClose" type="button" aria-label="Close">&#10005;</button></div><div class="ska-sheet-body" id="skaBody"></div></div>';
  var trigger=document.getElementById('skaTrigger'),status=document.getElementById('skaStatus'),backdrop=document.getElementById('skaBackdrop'),sheet=document.getElementById('skaSheet'),closeBtn=document.getElementById('skaClose'),body=document.getElementById('skaBody');
  function openSheet(){backdrop.classList.add('ska-show');sheet.classList.add('ska-show');sheet.setAttribute('aria-hidden','false');trigger.setAttribute('aria-expanded','true');}
  function closeSheet(){backdrop.classList.remove('ska-show');sheet.classList.remove('ska-show');sheet.setAttribute('aria-hidden','true');trigger.setAttribute('aria-expanded','false');}
  trigger.addEventListener('click',function(){if(sheet.classList.contains('ska-show'))closeSheet();else openSheet();});closeBtn.addEventListener('click',closeSheet);backdrop.addEventListener('click',closeSheet);document.addEventListener('keydown',function(e){if(e.key==='Escape')closeSheet();});
  function displayName(user){var m=(user&&user.user_metadata)||{};return m.full_name||m.name||m.user_name||'SnehaKoota Member';}
  function inviteEntry(){return '<button type="button" class="ska-action-row" id="skaInviteFriend">'+INVITE_ICON+'<span><strong>Invite a friend</strong><small>Share SnehaKoota with your friends</small></span></button>';}
  function bindProviderActions(){document.querySelectorAll('#skaBody [data-provider]').forEach(function(btn){btn.addEventListener('click',function(){var provider=providers.filter(function(pr){return pr.id===btn.getAttribute('data-provider');})[0];if(provider&&typeof provider.action==='function')provider.action(btn);});});}
  function invitationUrl(path){return window.location.origin+(path||'/');}
  function setInvitationButtons(disabled){var copy=document.getElementById('skaCopyInvite'),share=document.getElementById('skaShareInvite'),generate=document.getElementById('skaGenerateInvite');if(copy)copy.disabled=disabled;if(share)share.disabled=disabled;if(generate)generate.disabled=disabled;}
  function showTemporaryMessage(text){var message=document.getElementById('skaInviteMessage');if(!message)return;message.textContent=text;window.clearTimeout(showTemporaryMessage.timer);showTemporaryMessage.timer=window.setTimeout(function(){var current=document.getElementById('skaInviteMessage');if(current)current.textContent='Your invitation is ready to share.';},INVITATION_SUCCESS_MESSAGE_MS);}
  function copyInvitationLink(){var input=document.getElementById('skaInviteLink');if(!input||!input.value||input.value==='Link will appear here'||input.value==='Generating...')return;function copied(){showTemporaryMessage('Link copied.');}function failed(){input.focus();input.select();try{document.execCommand('copy');copied();}catch(e){showTemporaryMessage('Copy ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.');}}if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(input.value).then(copied).catch(failed);}else{failed();}}
  function shareInvitationLink(){var input=document.getElementById('skaInviteLink');if(!input||!input.value||input.value==='Link will appear here'||input.value==='Generating...')return;if(navigator.share){navigator.share({title:'SnehaKoota Invitation',text:'You are invited to SnehaKoota.',url:input.value}).then(function(){showTemporaryMessage('Invitation shared.');}).catch(function(err){if(err&&err.name==='AbortError')return;showTemporaryMessage('Share ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.');});}else{copyInvitationLink();}}
  function selectedMembershipIds(){var selected=[];document.querySelectorAll('#skaMembershipOptions input[data-membership-id]:checked').forEach(function(input){selected.push(Number(input.getAttribute('data-membership-id')));});return selected;}
  function isGeneralSelected(){var general=document.getElementById('skaGeneralInvitation');return !!(general&&general.checked);}
  function updateInvitationSelectionState(){var general=document.getElementById('skaGeneralInvitation'),boxes=document.querySelectorAll('#skaMembershipOptions input[data-membership-id]'),generate=document.getElementById('skaGenerateInvite'),ids=selectedMembershipIds(),valid=isGeneralSelected()||ids.length>0;if(general&&general.checked)boxes.forEach(function(box){box.checked=false;});boxes.forEach(function(box){box.disabled=!!(general&&general.checked);});if(generate)generate.disabled=!valid;}
  function handleGeneralInvitationChange(){var general=document.getElementById('skaGeneralInvitation');if(general&&general.checked)document.querySelectorAll('#skaMembershipOptions input[data-membership-id]').forEach(function(box){box.checked=false;});updateInvitationSelectionState();}
  function handleMembershipChange(){var boxes=document.querySelectorAll('#skaMembershipOptions input[data-membership-id]'),general=document.getElementById('skaGeneralInvitation');var anySelected=false;boxes.forEach(function(box){if(box.checked)anySelected=true;});if(anySelected&&general)general.checked=false;updateInvitationSelectionState();}
  function generateInvitation(){var input=document.getElementById('skaInviteLink'),message=document.getElementById('skaInviteMessage'),copy=document.getElementById('skaCopyInvite'),share=document.getElementById('skaShareInvite'),generate=document.getElementById('skaGenerateInvite'),ids=selectedMembershipIds(),membershipIds=isGeneralSelected()?[]:ids;if(INVITATION_MEMBERSHIP_MODE==='required'&&membershipIds.length===0){if(message)message.textContent='Choose at least one membership to create an invitation.';return;}if(input)input.value='Generating...';if(generate)generate.disabled=true;if(copy)copy.disabled=true;if(share)share.disabled=true;if(message)message.textContent='Creating your invitation…';supabaseClient.rpc('create_invitation',{p_membership_ids:membershipIds}).then(function(res){if(res.error){console.error('Invitation RPC error:',res.error);if(input)input.value='Link will appear here';if(message)message.textContent='Invitation could not be created. Please try again.';updateInvitationSelectionState();return;}var data=res.data;if(!data||!data.success){if(input)input.value='Link will appear here';if(message)message.textContent=(data&&data.message)||'Invitation could not be created. Please try again.';updateInvitationSelectionState();return;}var url=invitationUrl(data.path);if(input)input.value=url;if(message){var count=membershipIds.length;var kind=count===0?'general Snehakoota invitation':count===1?'membership invitation':'multi-membership invitation';message.textContent='Your '+kind+' is ready. Expires in 5 days.';}if(copy)copy.disabled=false;if(share)share.disabled=false;updateInvitationSelectionState();}).catch(function(err){console.error('Invitation generation error:',err);if(input)input.value='Link will appear here';if(message)message.textContent='Invitation could not be created. Please try again.';updateInvitationSelectionState();});}
  function populateMemberships(rows){var container=document.getElementById('skaMembershipOptions');if(!container)return;container.innerHTML='';(rows||[]).forEach(function(row){if(row.status!=='active')return;var label=document.createElement('label');label.className='ska-membership-option';var input=document.createElement('input');input.type='checkbox';input.setAttribute('data-membership-id',String(row.membership_id));var text=document.createElement('span');text.className='ska-membership-option-text';var school=row.school_name||'Snehakoota';var batch=row.batch_year?String(row.batch_year):'';text.innerHTML='<strong>'+school+'</strong><small>'+batch+'</small>';label.appendChild(input);label.appendChild(text);container.appendChild(label);});container.querySelectorAll('input[data-membership-id]').forEach(function(input){input.addEventListener('change',handleMembershipChange);});}
  function loadInvitationMemberships(){var container=document.getElementById('skaMembershipOptions'),message=document.getElementById('skaInviteMessage');if(!container)return;container.setAttribute('aria-busy','true');if(message)message.textContent='Loading your memberships…';supabaseClient.rpc('get_my_memberships').then(function(res){container.removeAttribute('aria-busy');if(res.error){console.error('Membership loading error:',res.error);populateMemberships([]);if(message)message.textContent='Could not load memberships. You can try again.';updateInvitationSelectionState();return;}populateMemberships(res.data||[]);if(message)message.textContent=INVITATION_MEMBERSHIP_MODE==='required'?'Choose one or more memberships.':'Choose one or more memberships, or create a general invitation.';updateInvitationSelectionState();});}
  function renderInvitationPanel(){body.innerHTML='<div class="ska-invite-panel"><button type="button" class="ska-back-btn" id="skaInviteBack" aria-label="Back">&#8592;<span>Account</span></button><h3 class="ska-auth-title">Invite a friend</h3><p class="ska-auth-sub">Choose the membership or memberships you want to include in this invitation.</p><div class="ska-membership-picker"><label class="ska-field-label">Memberships</label><div class="ska-membership-options" id="skaMembershipOptions"></div>'+(INVITATION_MEMBERSHIP_MODE!=='required'&&INVITATION_SHOW_GENERAL_OPTION?'<label class="ska-membership-option ska-general-option"><input type="checkbox" id="skaGeneralInvitation"><span class="ska-membership-option-text"><strong>General Snehakoota invitation</strong><small>Let your friend choose their membership later</small></span></label>':'')+'</div><button type="button" class="ska-invite-generate" id="skaGenerateInvite" disabled>Generate invitation</button><div class="ska-invite-link-wrap"><label class="ska-field-label" for="skaInviteLink">Invitation link</label><input class="ska-field ska-invite-link" id="skaInviteLink" type="text" value="Link will appear here" readonly></div><div class="ska-invite-actions"><button type="button" class="ska-invite-btn" id="skaCopyInvite" disabled>Copy</button><button type="button" class="ska-invite-btn ska-invite-share" id="skaShareInvite" disabled>Share</button></div><div class="ska-message" id="skaInviteMessage">Loading…</div></div>';document.getElementById('skaInviteBack').addEventListener('click',function(){renderSignedIn(currentSession);});var general=document.getElementById('skaGeneralInvitation');if(general)general.addEventListener('change',handleGeneralInvitationChange);document.getElementById('skaGenerateInvite').addEventListener('click',generateInvitation);document.getElementById('skaCopyInvite').addEventListener('click',copyInvitationLink);document.getElementById('skaShareInvite').addEventListener('click',shareInvitationLink);loadInvitationMemberships();}
  var currentSession=null;
  function bindSignedInControls(){bindReceiverInvitationContext();var inviteBtn=document.getElementById('skaInviteFriend'),confirmBtn=document.getElementById('skaConfirmInvitation'),ignoreBtn=document.getElementById('skaIgnoreInvitation'),passkeyBtn=document.getElementById('skaRegisterPasskey'),signOutBtn=document.getElementById('skaSignOut'),message=document.getElementById('skaMessage');if(inviteBtn)inviteBtn.addEventListener('click',function(){renderInvitationPanel();});if(confirmBtn)confirmBtn.addEventListener('click',processReceiverInvitation);if(ignoreBtn)ignoreBtn.addEventListener('click',ignoreReceiverInvitation);if(passkeyBtn)passkeyBtn.addEventListener('click',function(){passkeyBtn.disabled=true;if(message)message.textContent='Passkey ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ…';if(!window.PublicKeyCredential||!navigator.credentials){if(message)message.textContent='ಈ ಸಾಧನ ಅಥವಾ ಬ್ರೌಸರ್‌ನಲ್ಲಿ Passkey ಬೆಂಬಲವಿಲ್ಲ.';passkeyBtn.disabled=false;return;}supabaseClient.auth.registerPasskey().then(function(res){if(res.error){console.error('Passkey registration error:',res.error);var duplicatePasskey=res.error.name==='InvalidStateError'||res.error.code==='invalid_state'||/already\s*(registered|exists)|credential.*already|already.*credential/i.test(res.error.message||'');if(duplicatePasskey){message.textContent='Passkey is already registered on this device.';passkeyBtn.disabled=false;setTimeout(closeSheet,1400);return;}message.textContent='Passkey ಹೊಂದಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';passkeyBtn.disabled=false;return;}message.textContent='Passkey ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ.';passkeyBtn.disabled=false;setTimeout(closeSheet,1400);});});if(signOutBtn)signOutBtn.addEventListener('click',function(){signOutBtn.disabled=true;if(message)message.textContent='ಸೈನ್ ಔಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ…';supabaseClient.auth.signOut().then(function(res){if(res.error){console.error('Sign-out error:',res.error);message.textContent='ಸೈನ್ ಔಟ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';signOutBtn.disabled=false;return;}clearInvitationContext();updateAccount(null);});});}
  function renderSignedOut(){body.innerHTML=renderReceiverInvitationContext()+'<h3 class="ska-auth-title">Sign in to SnehaKoota</h3><p class="ska-auth-sub">Save your contributions and come back anytime.</p><div class="ska-providers">'+providers.map(function(p){return '<button type="button" class="ska-provider-btn '+p.style+'" data-provider="'+p.id+'">'+p.icon+'<span>'+p.label+'</span></button>';}).join('')+'</div><div class="ska-message" id="skaMessage"></div>';bindReceiverInvitationContext();bindProviderActions();}
  function renderSignedIn(session){currentSession=session;var user=session.user;body.innerHTML=renderReceiverInvitationContext()+renderReceiverProcessingAction()+'<h3 class="ska-auth-title">Signed in</h3><div class="ska-identity"><strong>'+displayName(user)+'</strong><span>'+ (user.email||'Google account')+'</span></div>'+inviteEntry()+'<button type="button" class="ska-provider-btn ska-secondary" id="skaRegisterPasskey">'+PASSKEY_ICON+'<span>Add a passkey to this device</span></button><button type="button" class="ska-signout-btn" id="skaSignOut">Sign out</button><div class="ska-message" id="skaMessage"></div>';bindSignedInControls();}
  function updateAccount(session){currentSession=session;var signedIn=!!(session&&session.user);trigger.classList.toggle('ska-signed-in',signedIn);status.title=signedIn?'Signed in':'Signed out';if(signedIn)renderSignedIn(session);else renderSignedOut();}
  var lastAuthState=null;function handleAuthStateChange(event,session){var signedIn=!!(session&&session.user);var previousSignedIn=lastAuthState;lastAuthState=signedIn;currentSession=session;trigger.classList.toggle('ska-signed-in',signedIn);status.title=signedIn?'Signed in':'Signed out';if((event==='SIGNED_IN'||event==='INITIAL_SESSION')&&signedIn&&hasInvitationAuthPending()){beginAuthenticatedInvitationProcessing();return;}if(event==='SIGNED_OUT'){renderSignedOut();return;}if(event==='INITIAL_SESSION'||previousSignedIn===null||signedIn!==previousSignedIn){if(signedIn)renderSignedIn(session);else renderSignedOut();}if(event==='SIGNED_IN'&&receiverInvitationContext.valid)maybeAutoOpenInvitation();}
  supabaseClient.auth.onAuthStateChange(handleAuthStateChange);supabaseClient.auth.getSession().then(function(res){if(res.error){console.error('Initial session error:',res.error);lastAuthState=false;updateAccount(null);return;}var session=res.data.session;var signedIn=!!(session&&session.user);lastAuthState=signedIn;updateAccount(session);if(signedIn&&hasInvitationAuthPending()&&(receiverInvitationContext.valid||loadStoredInvitationContext()))beginAuthenticatedInvitationProcessing();else if(receiverInvitationContext.valid)maybeAutoOpenInvitation();});
})();