/* Baraha reader presentation component. No Supabase calls belong here. */
(function(window){
"use strict";
class BarahaReader{
 constructor(options){options=options||{};this.root=options.root||document.getElementById("barahaReader");this.panel=options.panel||(this.root&&this.root.querySelector(".baraha-reader__panel"));this.closeButton=options.closeButton||document.getElementById("barahaReaderClose");this.returnButton=options.returnButton||document.getElementById("barahaReaderReturn");this.meta=options.meta||document.getElementById("barahaReaderMeta");this.title=options.title||document.getElementById("barahaReaderTitle");this.author=options.author||document.getElementById("barahaReaderAuthor");this.content=options.content||document.getElementById("barahaReaderContent");this.footer=options.footer||document.getElementById("barahaReaderFooter");this.headerActions=options.headerActions||document.getElementById("barahaReaderHeaderActions");this.currentPost=null;this.closeHandler=typeof options.onClose==="function"?options.onClose:null;if(!this.root||!this.panel)throw new Error("BarahaReader requires the reader panel shell.");if(this.closeButton)this.closeButton.addEventListener("click",()=>this.close());if(this.returnButton)this.returnButton.addEventListener("click",()=>this.close());this.root.addEventListener("click",(event)=>{if(event.target===this.root)this.close();});}
 render(post){this.currentPost=post||null;if(!post){this.clear();return;}const uiPost=window.BarahaView&&typeof window.BarahaView.postToUi==="function"?window.BarahaView.postToUi(post):post;const authorName=uiPost.author||post.authorDisplayName||"Member";const metaParts=[uiPost.categoryLabel||uiPost.category||"",uiPost.visibilityLabel||uiPost.visibility||""].filter(Boolean);const authorParts=[authorName,uiPost.displayTime||uiPost.time||""].filter(Boolean);this.panel.classList.remove("is-poem","is-memory","is-book");if(uiPost.presentation)this.panel.classList.add("is-"+uiPost.presentation);this.meta.textContent=metaParts.join(" · ");this.title.textContent=uiPost.title||"";this.author.textContent=authorParts.join(" · ");this.content.textContent=uiPost.content||"";this.footer.innerHTML="";this.headerActions.innerHTML=`<button class="baraha-reader__action" id="barahaReaderShare" type="button" aria-label="ಹಂಚಿಕೊಳ್ಳಿ" title="ಹಂಚಿಕೊಳ್ಳಿ"><svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" focusable="false"><path d="M12 16V4m0 0-4 4m4-4 4 4M5 12v7h14v-7"></path></svg></button>`;const shareButton=this.headerActions.querySelector("#barahaReaderShare");if(shareButton)shareButton.addEventListener("click",()=>this.shareCurrentPost());}
 open(post){if(post)this.render(post);if(!this.currentPost)throw new Error("BarahaReader.open requires a post.");this.root.classList.add("is-open");this.root.setAttribute("aria-hidden","false");this.panel.scrollTop=0;document.body.classList.add("baraha-reader-open");const body=document.getElementById("barahaReaderBody");if(body)body.focus();}
 getShareUrl(){if(!this.currentPost||this.currentPost.id===null||this.currentPost.id===undefined||this.currentPost.id==="")return "";const url=new URL(window.location.href);url.searchParams.set("post",String(this.currentPost.id));return url.toString();}
 async copyText(text){if(!text)return false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true;}}catch(error){}const textarea=document.createElement("textarea");textarea.value=text;textarea.setAttribute("readonly","");textarea.style.position="fixed";textarea.style.opacity="0";document.body.appendChild(textarea);textarea.select();let copied=false;try{copied=document.execCommand("copy");}catch(error){}textarea.remove();return copied;}
 async shareCurrentPost(){if(!this.currentPost)return;const url=this.getShareUrl();if(!url)return;const title=this.title.textContent||"Snehakoota";const text="Kindly have a look at this post in Snehakoota.in";const copyPromise=this.copyText(url);if(typeof navigator.share==="function"){try{await navigator.share({title,text,url});}catch(error){if(error&&error.name!=="AbortError")await copyPromise;}}else{await copyPromise;}}
 close(){this.root.classList.remove("is-open");this.root.setAttribute("aria-hidden","true");document.body.classList.remove("baraha-reader-open");if(this.closeHandler)this.closeHandler();}
 setCloseHandler(handler){this.closeHandler=typeof handler==="function"?handler:null;}
 clear(){this.currentPost=null;this.meta.textContent="";this.title.textContent="";this.author.textContent="";this.content.textContent="";this.footer.innerHTML="";this.headerActions.innerHTML="";this.panel.classList.remove("is-poem","is-memory","is-book");}
 isOpen(){return this.root.classList.contains("is-open");}
}
window.BarahaReader=BarahaReader;
})(window);