-- Community Updates / Notices foundation baseline.
-- This baseline represents foundation objects created before remote migration tracking was reconciled.
-- It is ordered before the reconciliation marker so fresh environments can build the foundation before later deltas.
-- Generic update model: notice, announcement, event.
-- Membership targeting uses school_batches (shared context), never user-specific memberships.

create table public.community_updates (
  id bigint generated by default as identity primary key,
  update_type text not null check (update_type in ('notice','announcement','event')),
  visibility_scope text not null check (visibility_scope in ('public','membership_targeted')),
  title text not null check (btrim(title) <> ''),
  content text,
  created_by uuid not null references auth.users(id) on delete restrict,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_updates_expiry_after_publish check (expires_at is null or expires_at > published_at)
);

create table public.community_update_memberships (
  update_id bigint not null references public.community_updates(id) on delete cascade,
  school_batch_id bigint not null references public.school_batches(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (update_id, school_batch_id)
);

create table public.community_update_event_details (
  update_id bigint primary key references public.community_updates(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz,
  location_name text,
  location_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_update_event_details_end_after_start check (ends_at is null or ends_at >= starts_at)
);

create index community_updates_active_public_idx on public.community_updates (published_at desc)
  where visibility_scope = 'public';
create index community_updates_expires_at_idx on public.community_updates (expires_at);
create index community_updates_type_published_idx on public.community_updates (update_type, published_at desc);
create index community_update_memberships_school_batch_idx
  on public.community_update_memberships (school_batch_id, update_id);

create or replace function public.community_updates_set_updated_at()
returns trigger language plpgsql set search_path to 'public' as $$
begin new.updated_at := now(); return new; end;
$$;

create trigger community_updates_set_updated_at before update on public.community_updates
for each row execute function public.community_updates_set_updated_at();
create trigger community_update_event_details_set_updated_at before update on public.community_update_event_details
for each row execute function public.community_updates_set_updated_at();

create or replace function public.community_updates_event_details_require_event()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  if not exists (select 1 from public.community_updates where id=new.update_id and update_type='event') then
    raise exception 'Event details are only valid for event updates';
  end if;
  return new;
end;
$$;
create trigger community_update_event_details_require_event
before insert or update on public.community_update_event_details
for each row execute function public.community_updates_event_details_require_event();

insert into public.site_config
(config_key,config_value,config_value_2,config_value_3,description,scope_type,scope_id,config_seq,data_type,is_active)
values
('community_updates_public_authority','allow','deny','deny',
 'Community Updates public publishing authority. config_value=OWNER, config_value_2=ADMIN, config_value_3=MEMBER. school_batch scope may grant authority to a specific batch role.',
 'global',null,1,'text',true)
on conflict do nothing;

create or replace function public.community_updates_is_active_school_batch_member(
  p_school_batch_id bigint, p_user_id uuid default auth.uid()
) returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists (
    select 1 from public.memberships m
    where m.batch_id=p_school_batch_id and m.user_id=p_user_id and m.status='active'
  );
$$;

create or replace function public.community_updates_is_active_school_batch_admin(
  p_school_batch_id bigint, p_user_id uuid default auth.uid()
) returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists (
    select 1 from public.memberships m
    where m.batch_id=p_school_batch_id and m.user_id=p_user_id
      and m.status='active' and m.membership_type='admin'
  );
$$;

create or replace function public.community_updates_can_publish_public(
  p_user_id uuid default auth.uid()
) returns boolean language plpgsql stable security definer set search_path to 'public' as $$
declare v_owner text; v_admin text; v_member text;
begin
  if p_user_id is null then return false; end if;
  select config_value,config_value_2,config_value_3 into v_owner,v_admin,v_member
  from public.site_config
  where config_key='community_updates_public_authority'
    and scope_type='global' and scope_id is null and is_active
  order by config_seq limit 1;

  if public.is_platform_owner() then return coalesce(v_owner,'deny')='allow'; end if;

  if exists (
    select 1 from public.memberships m join public.site_config c
      on c.config_key='community_updates_public_authority'
     and c.scope_type='school_batch' and c.scope_id=m.batch_id and c.is_active
    where m.user_id=p_user_id and m.status='active'
      and ((m.membership_type='admin' and c.config_value_2='allow')
        or (m.membership_type='member' and c.config_value_3='allow'))
  ) then return true; end if;

  return exists (
    select 1 from public.memberships m
    where m.user_id=p_user_id and m.status='active'
      and ((m.membership_type='admin' and coalesce(v_admin,'deny')='allow')
        or (m.membership_type='member' and coalesce(v_member,'deny')='allow'))
  );
end;
$$;

create or replace function public.community_updates_can_manage_targets(
  p_school_batch_ids bigint[], p_user_id uuid default auth.uid()
) returns boolean language plpgsql stable security definer set search_path to 'public' as $$
begin
  if p_user_id is null or p_school_batch_ids is null or cardinality(p_school_batch_ids)=0 then return false; end if;
  if public.is_platform_owner() then return true; end if;
  return not exists (
    select 1 from (select distinct x as school_batch_id from unnest(p_school_batch_ids) x where x is not null) t
    where not public.community_updates_is_active_school_batch_admin(t.school_batch_id,p_user_id)
  );
end;
$$;

create or replace function public.community_updates_can_read(
  p_update_id bigint, p_user_id uuid default auth.uid()
) returns boolean language plpgsql stable security definer set search_path to 'public' as $$
declare v public.community_updates;
begin
  select * into v from public.community_updates where id=p_update_id;
  if not found then return false; end if;
  if p_user_id is not null and (
    public.is_platform_owner() or v.created_by=p_user_id or
    (v.visibility_scope='membership_targeted' and exists (
      select 1 from public.community_update_memberships t
      where t.update_id=v.id and public.community_updates_is_active_school_batch_admin(t.school_batch_id,p_user_id)
    ))
  ) then return true; end if;
  if v.expires_at is not null and v.expires_at<=now() then return false; end if;
  if v.visibility_scope='public' then return true; end if;
  return p_user_id is not null and exists (
    select 1 from public.community_update_memberships t
    where t.update_id=v.id and public.community_updates_is_active_school_batch_member(t.school_batch_id,p_user_id)
  );
end;
$$;

create or replace function public.community_updates_can_manage(
  p_update_id bigint, p_user_id uuid default auth.uid()
) returns boolean language plpgsql stable security definer set search_path to 'public' as $$
declare v_visibility text; v_targets bigint[];
begin
  if p_user_id is null then return false; end if;
  select visibility_scope into v_visibility from public.community_updates where id=p_update_id;
  if not found then return false; end if;
  if v_visibility='public' then return public.community_updates_can_publish_public(p_user_id); end if;
  select array_agg(school_batch_id order by school_batch_id) into v_targets
  from public.community_update_memberships where update_id=p_update_id;
  return public.community_updates_can_manage_targets(v_targets,p_user_id);
end;
$$;

create or replace function public.community_updates_save(
  p_update_id bigint default null,
  p_update_type text default null,
  p_visibility_scope text default null,
  p_title text default null,
  p_content text default null,
  p_expires_at timestamptz default null,
  p_school_batch_ids bigint[] default null,
  p_event_starts_at timestamptz default null,
  p_event_ends_at timestamptz default null,
  p_event_location_name text default null,
  p_event_location_url text default null
) returns public.community_updates language plpgsql security definer set search_path to 'public' as $$
declare v_user uuid:=auth.uid(); v public.community_updates; v_targets bigint[]; v_count int;
begin
  if v_user is null then raise exception 'Authentication is required'; end if;
  if p_update_type not in ('notice','announcement','event') then raise exception 'Unsupported update type'; end if;
  if p_visibility_scope not in ('public','membership_targeted') then raise exception 'Unsupported visibility scope'; end if;
  if p_title is null or btrim(p_title)='' then raise exception 'Community Update title is required'; end if;
  if p_expires_at is not null and p_expires_at<=now() then raise exception 'expires_at must be in the future'; end if;

  select array_agg(distinct x order by x),count(distinct x) into v_targets,v_count
  from unnest(coalesce(p_school_batch_ids,'{}'::bigint[])) x where x is not null;

  if p_visibility_scope='public' then
    if coalesce(v_count,0)<>0 then raise exception 'Public updates cannot have school-batch targets'; end if;
    if not public.community_updates_can_publish_public(v_user) then raise exception 'Not allowed to publish public Community Updates'; end if;
  else
    if coalesce(v_count,0)=0 then raise exception 'At least one school-batch target is required'; end if;
    if exists (select 1 from unnest(v_targets) x where not exists (
      select 1 from public.school_batches sb where sb.id=x and sb.is_active
    )) then raise exception 'Invalid or inactive school-batch target'; end if;
    if not public.community_updates_can_manage_targets(v_targets,v_user) then
      raise exception 'You must be an active admin of every targeted school batch';
    end if;
  end if;

  if p_update_type='event' then
    if p_event_starts_at is null then raise exception 'Event start time is required'; end if;
    if p_event_ends_at is not null and p_event_ends_at<p_event_starts_at then raise exception 'Event end time cannot be before event start time'; end if;
  elsif p_event_starts_at is not null or p_event_ends_at is not null
     or nullif(btrim(coalesce(p_event_location_name,'')),'') is not null
     or nullif(btrim(coalesce(p_event_location_url,'')),'') is not null then
    raise exception 'Event details are only valid for event updates';
  end if;

  if p_update_id is null then
    insert into public.community_updates(update_type,visibility_scope,title,content,created_by,published_at,expires_at)
    values(p_update_type,p_visibility_scope,btrim(p_title),nullif(btrim(coalesce(p_content,'')),''),v_user,now(),p_expires_at)
    returning * into v;
  else
    if not public.community_updates_can_manage(p_update_id,v_user) then raise exception 'Not allowed to manage this Community Update'; end if;
    update public.community_updates set update_type=p_update_type,visibility_scope=p_visibility_scope,
      title=btrim(p_title),content=nullif(btrim(coalesce(p_content,'')),''),expires_at=p_expires_at
    where id=p_update_id returning * into v;
  end if;

  delete from public.community_update_memberships where update_id=v.id;
  if p_visibility_scope='membership_targeted' then
    insert into public.community_update_memberships(update_id,school_batch_id)
    select v.id,x from unnest(v_targets) x;
  end if;

  delete from public.community_update_event_details where update_id=v.id;
  if p_update_type='event' then
    insert into public.community_update_event_details(update_id,starts_at,ends_at,location_name,location_url)
    values(v.id,p_event_starts_at,p_event_ends_at,
      nullif(btrim(coalesce(p_event_location_name,'')),''),nullif(btrim(coalesce(p_event_location_url,'')),'')); 
  end if;
  return v;
end;
$$;

create or replace function public.community_updates_delete(p_update_id bigint)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  if auth.uid() is null then raise exception 'Authentication is required'; end if;
  if not public.community_updates_can_manage(p_update_id,auth.uid()) then raise exception 'Not allowed to delete this Community Update'; end if;
  delete from public.community_updates where id=p_update_id;
  if not found then raise exception 'Community Update not found'; end if;
end;
$$;

alter table public.community_updates enable row level security;
alter table public.community_update_memberships enable row level security;
alter table public.community_update_event_details enable row level security;

create policy community_updates_select_allowed on public.community_updates
for select to anon,authenticated using (public.community_updates_can_read(id,auth.uid()));
create policy community_update_memberships_select_allowed on public.community_update_memberships
for select to authenticated using (public.community_updates_can_read(update_id,auth.uid()));
create policy community_update_event_details_select_allowed on public.community_update_event_details
for select to anon,authenticated using (public.community_updates_can_read(update_id,auth.uid()));

revoke all on table public.community_updates from anon,authenticated;
revoke all on table public.community_update_memberships from anon,authenticated;
revoke all on table public.community_update_event_details from anon,authenticated;
grant select on public.community_updates to anon,authenticated;
grant select on public.community_update_event_details to anon,authenticated;
grant select on public.community_update_memberships to authenticated;

revoke all on function public.community_updates_is_active_school_batch_member(bigint,uuid) from public;
revoke all on function public.community_updates_is_active_school_batch_admin(bigint,uuid) from public;
revoke all on function public.community_updates_can_publish_public(uuid) from public;
revoke all on function public.community_updates_can_manage_targets(bigint[],uuid) from public;
revoke all on function public.community_updates_can_read(bigint,uuid) from public;
revoke all on function public.community_updates_can_manage(bigint,uuid) from public;
revoke all on function public.community_updates_save(bigint,text,text,text,text,timestamptz,bigint[],timestamptz,timestamptz,text,text) from public;
revoke all on function public.community_updates_delete(bigint) from public;
grant execute on function public.community_updates_save(bigint,text,text,text,text,timestamptz,bigint[],timestamptz,timestamptz,text,text) to authenticated;
grant execute on function public.community_updates_delete(bigint) to authenticated;
